name: EnglishJobLinks
favicon: null
layout_spectrum: 0.23656
typography_spectrum: 0.50589
title: EnglishJobLinks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#977025'
    - '#00a14b'
    - '#ec008b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.42340057296678424
purpose: []
